# Generated by Django 4.0.4 on 2022-04-27 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stocktick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Plant', models.CharField(max_length=50)),
                ('Godown', models.CharField(max_length=50)),
                ('OurLot', models.IntegerField()),
                ('RecdDate', models.DateField()),
                ('Type', models.CharField(max_length=10)),
                ('Garden', models.CharField(max_length=100)),
                ('Grade', models.CharField(max_length=50)),
                ('InvNo', models.CharField(max_length=50)),
                ('Cases', models.IntegerField()),
                ('Kg', models.FloatField()),
                ('NetKg', models.FloatField()),
                ('RowNo', models.CharField(max_length=50)),
                ('Remarks', models.TextField(max_length=500)),
                ('Status', models.BooleanField(default=True)),
                ('Pcase', models.IntegerField(default=0)),
            ],
        ),
    ]
