# Generated by Django 4.0.4 on 2022-04-25 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stocktick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant', models.CharField(max_length=50)),
                ('godown', models.IntegerField()),
                ('our_lot', models.IntegerField()),
                ('recd_date', models.DateField()),
                ('types', models.CharField(max_length=10)),
                ('garden', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=50)),
                ('inv_no', models.CharField(max_length=50)),
                ('cases', models.IntegerField()),
                ('kg', models.IntegerField()),
                ('net_Kg', models.FloatField()),
                ('row_no', models.CharField(max_length=50)),
                ('remarks', models.TextField(max_length=500)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
