# Generated by Django 4.0.4 on 2022-04-25 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Table', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stocktick',
            old_name='net_Kg',
            new_name='net_kg',
        ),
    ]
