# Generated by Django 4.0.4 on 2022-05-11 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Table', '0003_stocktick_updated_at_alter_stocktick_updated_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeaBag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PacketId', models.IntegerField()),
                ('OurLot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Table.stocktick')),
            ],
        ),
    ]
