# Generated by Django 4.0.4 on 2022-05-12 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Table', '0004_teabag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teabag',
            name='PacketId',
            field=models.IntegerField(unique=True),
        ),
    ]
