# Generated by Django 4.0.4 on 2022-05-12 23:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Table', '0005_alter_teabag_packetid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktick',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updatedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teabag',
            name='OurLot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ourlots', to='Table.stocktick'),
        ),
    ]
